/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.EmployeeRole;
import java.io.IOException;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class AddProduct extends javax.swing.JFrame implements Loop {

    /**
     * Creates new form AddProduct
     */
    EmployeeRole emp;
    Loop parent;

    public AddProduct(EmployeeRole emp) {
        initComponents();
        this.emp = emp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JLabel();
        productID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        manufacturerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        supplierName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        addProduct = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ID.setBackground(new java.awt.Color(153, 204, 255));
        ID.setText("       Product ID");
        ID.setOpaque(true);

        productID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIDActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("    Product Name");
        jLabel1.setOpaque(true);

        productName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setText("Manufacturer Name");
        jLabel2.setOpaque(true);

        manufacturerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturerNameActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 204, 255));
        jLabel3.setText("    Supplier Name");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(153, 204, 255));
        jLabel4.setText("        Quantity");
        jLabel4.setOpaque(true);

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        addProduct.setBackground(new java.awt.Color(0, 0, 0));
        addProduct.setForeground(new java.awt.Color(255, 255, 255));
        addProduct.setText("Add");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 204, 255));
        jLabel5.setText("          Price");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productID, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(price, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(productName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(manufacturerName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(supplierName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(quantity, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(productID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(productName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(manufacturerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(supplierName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(quantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(price))
                .addGap(18, 18, 18)
                .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    private void manufacturerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerNameActionPerformed

    private void productIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIDActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed


    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed

        if (productID.getText().isEmpty() || productName.getText().isEmpty() || manufacturerName.getText().isEmpty() || supplierName.getText().isEmpty() || quantity.getText().isEmpty() || price.getText().isEmpty()) {
            this.setVisible(false);//check if any text field is empty, close the window to show a warning message then open it again when it's closed
            JOptionPane.showMessageDialog(null, "Some fields are empty");
            productID.setText("");
            productName.setText("");
            manufacturerName.setText("");
            supplierName.setText("");
            quantity.setText("");
            price.setText("");
            this.setVisible(true);
        } else {
            boolean x = true;
            {
                try {
                    int m = Integer.parseInt(quantity.getText().trim());
                } catch (Exception ex) {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "You should enter a numeric value in the field whose name is \"Quantity\" ");
                    x = false;
                    this.setVisible(true);
                     productID.setText("");
                    productName.setText("");
                    manufacturerName.setText("");
                    supplierName.setText("");
                    quantity.setText("");
                    price.setText("");
                }
                try {
                    float n = Integer.parseInt(price.getText().trim());
                } catch (Exception ex) {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "You should enter a numeric value in the field whose name is \"Price\" ");
                    x = false;
                    this.setVisible(true);
                     productID.setText("");
                    productName.setText("");
                    manufacturerName.setText("");
                    supplierName.setText("");
                    quantity.setText("");
                    price.setText("");
                }
                if (x) {
                    try {
                        if (emp.contains(productID.getText().trim())) {//check if the id is existed 
                            this.setVisible(false);//close window to show the following text
                            JOptionPane.showMessageDialog(null, "The product with id:" + productID.getText() + " already exists!");
                        } else {
                            emp.addProduct(productID.getText().trim(), productName.getText().trim(), manufacturerName.getText().trim(), supplierName.getText().trim(), parseInt(quantity.getText().trim()), Float.parseFloat(price.getText().trim()));
                            this.setVisible(false);//if id already exists then close the window to show the following text 
                            JOptionPane.showMessageDialog(null, "The product with id:" + productID.getText() + " is added");
                        }
                    } catch (IOException ex) {
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "An error occuired while entering data");//if an error happened while reading data from file for adminrole class
                    }
                    productID.setText("");
                    productName.setText("");
                    manufacturerName.setText("");
                    supplierName.setText("");
                    quantity.setText("");
                    price.setText("");
                    this.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_addProductActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame) getParentLoop()).setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton addProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField manufacturerName;
    private javax.swing.JTextField price;
    private javax.swing.JTextField productID;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField supplierName;
    // End of variables declaration//GEN-END:variables
    @Override

    public Loop getParentLoop() {
        return this.parent;
    }

    @Override

    public void setParentLoop(Loop loop) {
        this.parent = loop;

    }
}
