package frontend;

import backend.AdminRole;
import backend.EmployeeUser;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class AdminRoleWindow extends javax.swing.JFrame implements Loop {
AdminRole admin;
Loop parent;
    /**
     * Creates new form AdminRoleWindow
     */
    public AdminRoleWindow(AdminRole admin) {
        initComponents();
        this.admin=admin;
         setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addEmp = new javax.swing.JButton();
        viewEmp = new javax.swing.JButton();
        removeEmp = new javax.swing.JButton();
        logOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Role");

        addEmp.setBackground(new java.awt.Color(0, 0, 0));
        addEmp.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        addEmp.setForeground(new java.awt.Color(255, 255, 255));
        addEmp.setText("Add Employee");
        addEmp.setPreferredSize(new java.awt.Dimension(107, 40));
        addEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpActionPerformed(evt);
            }
        });

        viewEmp.setBackground(new java.awt.Color(0, 0, 0));
        viewEmp.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        viewEmp.setForeground(new java.awt.Color(255, 255, 255));
        viewEmp.setText("View Employees");
        viewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmpActionPerformed(evt);
            }
        });

        removeEmp.setBackground(new java.awt.Color(0, 0, 0));
        removeEmp.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        removeEmp.setForeground(new java.awt.Color(255, 255, 255));
        removeEmp.setText("Remove Employee");
        removeEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmpActionPerformed(evt);
            }
        });

        logOut.setBackground(new java.awt.Color(0, 0, 0));
        logOut.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("Logout");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(viewEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(addEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(viewEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(removeEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpActionPerformed
        AddEmployee add=new AddEmployee(admin);//the add button if entered, action taken is creating an object from addemployee window
        add.setVisible(true);//make addemployee window visible and close adminrole window
        this.setVisible(false);
        add.setParentLoop(this);
    }//GEN-LAST:event_addEmpActionPerformed

    private void viewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmpActionPerformed
        String[]colNames={"EmployeeID","Name","Email","Address","Phone Number"};//set columns names in an array of strings
        ViewEmployees vemp = new ViewEmployees(admin, colNames);//create object of viewemployees window to open later
        EmployeeUser[] data = admin.getListOfEmployees();//get list of employees saved in adminrole class and save them in an array to pass them to the table
        String [][]table=new String[data.length][5];//matrix "rows=employees data" "columns=titles like name email etc", this matrix will be passed to the viewing window
        for (int i = 0; i < data.length; i++) {
            table[i]= data[i].lineRepresentation().split(",");//loop on data to store employee's data "split on comma" in table 
        }
        vemp.setTitle("View Employees");//title of the window
        vemp.tableData(table);//passing table matrix to viewemployee wiindow, where it will be set in a customized model  
        vemp.setParentLoop(this);//making this window a parent window to viewemployees so that it's opended back after closing viewemloyees window
        vemp.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_viewEmpActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        try {
            admin.logout();
            this.setVisible(false);
        ((JFrame)getParentLoop()).setVisible(true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error appeared while opening main window");
        }
    }//GEN-LAST:event_logOutActionPerformed

    private void removeEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmpActionPerformed
 RemoveEmployee remove=new RemoveEmployee(admin);
        remove.setVisible(true);
        this.setVisible(false);
         remove.setParentLoop(this);
    }//GEN-LAST:event_removeEmpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmp;
    private javax.swing.JButton logOut;
    private javax.swing.JButton removeEmp;
    private javax.swing.JButton viewEmp;
    // End of variables declaration//GEN-END:variables

    @Override
    public Loop getParentLoop() {
        return this.parent;
    }

    @Override
    public void setParentLoop(Loop loop) {
this.parent=loop;
    }
}
