package frontend;

import backend.EmployeeRole;
import backend.CustomerProduct;
import backend.Product;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class EmployeeRoleWindow extends javax.swing.JFrame implements Loop {

    /**
     * Creates new form EmployeeRoleWindow
     */
    EmployeeRole employee;
    Loop parent;

    public EmployeeRoleWindow(EmployeeRole employee) {
        initComponents();
        this.employee = employee;
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProduct = new javax.swing.JButton();
        viewProducts = new javax.swing.JButton();
        purchaseProduct = new javax.swing.JButton();
        viewPurchasedProducts = new javax.swing.JButton();
        returnProduct = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setTitle("Employee Role");

        addProduct.setBackground(new java.awt.Color(0, 0, 0));
        addProduct.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        addProduct.setForeground(new java.awt.Color(255, 255, 255));
        addProduct.setText("Add Product");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        viewProducts.setBackground(new java.awt.Color(0, 0, 0));
        viewProducts.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        viewProducts.setForeground(new java.awt.Color(255, 255, 255));
        viewProducts.setText("View Products");
        viewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductsActionPerformed(evt);
            }
        });

        purchaseProduct.setBackground(new java.awt.Color(0, 0, 0));
        purchaseProduct.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        purchaseProduct.setForeground(new java.awt.Color(255, 255, 255));
        purchaseProduct.setText("Purchase Product");
        purchaseProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseProductActionPerformed(evt);
            }
        });

        viewPurchasedProducts.setBackground(new java.awt.Color(0, 0, 0));
        viewPurchasedProducts.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        viewPurchasedProducts.setForeground(new java.awt.Color(255, 255, 255));
        viewPurchasedProducts.setText("View Purchased Products");
        viewPurchasedProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPurchasedProductsActionPerformed(evt);
            }
        });

        returnProduct.setBackground(new java.awt.Color(0, 0, 0));
        returnProduct.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        returnProduct.setForeground(new java.awt.Color(255, 255, 255));
        returnProduct.setText("Return Product");
        returnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnProductActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewPurchasedProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(purchaseProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(returnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(purchaseProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewPurchasedProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        AddProduct add = new AddProduct(employee);//creating an object from addproduct window
        add.setVisible(true);//make addproduct window visible and close adminrole window
        this.setVisible(false);
         add.setParentLoop(this);    }//GEN-LAST:event_addProductActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        try {
            employee.logout();
            this.setVisible(false);
            ((JFrame) getParentLoop()).setVisible(true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error appeared while opening main window");
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void viewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductsActionPerformed
        String[] colNames = {"productID", " productName", "manufacturerName", "supplierName", "quantity", " price"};//set columns names in an array of strings
        ViewProducts vemp = new ViewProducts(employee, colNames);//create object of viewproducts window to open later
        Product[] data = employee.getListOfProducts();//get list of products save them in an array to pass them to the table
        String[][] table = new String[data.length][6];//matrix "rows= data" "columns=titles like name email etc", this matrix will be passed to the viewing window
        for (int i = 0; i < data.length; i++) {
            table[i] = data[i].lineRepresentation().split(",");//loop on data to store Products's data "split on comma" in table 
        }
        vemp.setTitle("View Products");//title of the window
        vemp.tableData(table);//passing table matrix to viewproducts wiindow, where it will be set in a customized model  
        vemp.setParentLoop(this);//making this window a parent window to viewProducts so that it's opended back after closing window
        vemp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewProductsActionPerformed

    private void purchaseProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseProductActionPerformed
        PurchaseProduct purchase = new PurchaseProduct(employee);
        purchase.setVisible(true);
        this.setVisible(false);
        purchase.setParentLoop(this);    }//GEN-LAST:event_purchaseProductActionPerformed

    private void viewPurchasedProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPurchasedProductsActionPerformed
        String[] colNames = {"EmployeeID", "Name", "Email", "Address", "Phone Number"};//set columns names in an array of strings
        ViewPurchasedProducts vproduct = new ViewPurchasedProducts(employee, colNames);//create object of viewpp window to open later
        CustomerProduct[] data = employee.getListOfPurchasingOperations();//get list of pp saved in class and save them in an array to pass them to the table
        String[][] table = new String[data.length][5];//matrix "rows=product data" "columns=titles like name etc", this matrix will be passed to the viewing window
        for (int i = 0; i < data.length; i++) {
            table[i] = data[i].lineRepresentation().split(",");//loop on data to store data "split on comma" in table 
        }
        vproduct.setTitle("View purchase products");//title of the window
        vproduct.tableData(table);//passing table matrix to view wiindow, where it will be set in a customized model  
        vproduct.setParentLoop(this);//making this window a parent window to view so that it's opended back after closing window
        vproduct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewPurchasedProductsActionPerformed

    private void returnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnProductActionPerformed
        ReturnProduct returnp = new ReturnProduct(employee);
        returnp.setParentLoop(this);
        returnp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnProductActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JButton logout;
    private javax.swing.JButton purchaseProduct;
    private javax.swing.JButton returnProduct;
    private javax.swing.JButton viewProducts;
    private javax.swing.JButton viewPurchasedProducts;
    // End of variables declaration//GEN-END:variables

    @Override
    public Loop getParentLoop() {
        return this.parent;
    }

    @Override
    public void setParentLoop(Loop loop) {
        this.parent = loop;
    }
}
